### ISSUE TITLE
Issue: type object 'Draft7Validator' has no attribute 'FORMAT_CHECKER'

### ISSUE THREAD

**Issue by driadi** [altair-viz/altair#2857]
Came here because I found this error when running Great Expectations and it seems that the issue occurred in v4.2.1. 

I haven't verified this yet but it seems that `jsonschema.Draft7Validator` only has `FORMAT_CHECKER` attribute since jsonschema >= v4.3.0 so perhaps the requirements file in this module needs to be updated?

**Comment by binste** [comment]
Thanks for reporting the bug! Indeed, a quick fix for anyone affected is to upgrade jsonschema.

@mattijn @joelostblom This is an urgent one. I already fixed it in #2812 but that PR never made its way into the 4.2.1 release. Probably because the PR was actually about something else and I just fixed this backwards compatibility issue on the side. Sorry for that! Should have kept these PRs better separated and spot it while reviewing #2844. I can't get in front of a laptop right now but I can create a PR against `v4.2.X` branch this evening for a `v4.2.2`release.

**Comment by mattijn** [comment]
Thanks for the report @driadi. While you were running Great Expectations, me was running 'to what extend did I just break the Internet?' 
No problem @binste! Thank you for willing to look into it this evening. 

So currently:

- Altair 4.2.0 works with jsonschema <=4.16.0
- Altair 4.2.1 works with jsonschema >=4.3.0

**Comment by binste** [comment]
Minor clarification:
* Altair 4.2.0 works with jsonschema >=3,<4.17
* Altair 4.2.1 works with jsonschema >=**4.17.0** (4.17.3 is the newest jsonschema version)

**Comment by mattijn** [comment]
Done per https://pypi.org/project/altair/4.2.2/
Thanks again @binste!
