### ISSUE TITLE
Accessing the value of alt.selection_single() directly?

### ISSUE THREAD

**Issue by MattJBritton** [altair-viz/altair#2014]
First thing I'd like to say if thanks for developing Altair, I use it all the time and am very grateful!

I am trying to directly access the value of a single selection. My own use case is a bit more complicated, but I hoped to leverage the basic method depicted [here](https://altair-viz.github.io/user_guide/interactions.html#selection-values-in-expressions), in the "Bindings, Selections, Conditions: Making Charts Interactive" page in the Altair documentation. The specific section is "Selection Values in Expressions". 

Essentially, it states that if my selection has the "field" property set, then I can access that value directly in a transform using selection.field. However, the basic example given (code copied below), does not work on Altair 4.0.0. I receive the following error: 

> 'Selection' object has no attribute 'cutoff'

Please advise on whether this is a bug, or if the functionality has been removed. If the latter, is there any way on 4.0 to access the value of a selector in an expression? 

```python
import altair as alt
import pandas as pd
import numpy as np

rand = np.random.RandomState(42)

df = pd.DataFrame({
    'xval': range(100),
    'yval': rand.randn(100).cumsum()
})

slider = alt.binding_range(min=0, max=100, step=1, name='cutoff:')
selector = alt.selection_single(name="SelectorName", fields=['cutoff'],
                                bind=slider, init={'cutoff': 50})

alt.Chart(df).mark_point().encode(
    x='xval',
    y='yval',
    color=alt.condition(
        alt.datum.xval < selector.cutoff,
        alt.value('red'), alt.value('blue')
    )
).add_selection(
    selector
)
```

**Comment by MattJBritton** [comment]
Apologies, 4.0.1 is my Altair version.

**Comment by jakevdp** [comment]
The above code works in Altair version 4.0.1.

If you are getting the error
```
'Selection' object has no attribute 'cutoff'
```
when running that code, then I suspect you are using Altair version 3.1 or older.

**Comment by MattJBritton** [comment]
Whoops, terribly sorry. Confusion between different environments. The code does work for me on 4.0.1, and apologies for wasting your time.
